const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');
const db = require('../db/connection');

exports.signup = async (req, res) => {
    const { email, password } = req.body;

    if (!email || !password) {
        return res.status(400).json({ error: 'Email and password are required' });
    }

    try {
        // 1. Hash the password
        const salt = await bcrypt.genSalt(10);
        const hashedPassword = await bcrypt.hash(password, salt);

        // 2. Insert user with a placeholder schema name first to get the ID
        // We use a transaction to ensure everything succeeds or fails together
        const client = await db.pool.connect();

        try {
            await client.query('BEGIN');

            const userInsertResult = await client.query(
                'INSERT INTO users (email, password, schema_name) VALUES ($1, $2, $3) RETURNING id',
                [email, hashedPassword, `temp_${Date.now()}`]
            );

            const userId = userInsertResult.rows[0].id;
            const schemaName = `user_${userId}`;

            // 3. Update the user with the correct schema name
            await client.query(
                'UPDATE users SET schema_name = $1 WHERE id = $2',
                [schemaName, userId]
            );

            // 4. Create the physical SCHEMA in PostgreSQL
            // Note: We use dynamic SQL here. This is safe because schemaName is generated by us.
            await client.query(`CREATE SCHEMA ${schemaName}`);

            await client.query('COMMIT');

            res.status(201).json({
                message: 'User registered successfully',
                user: { id: userId, email, schemaName }
            });
        } catch (err) {
            await client.query('ROLLBACK');
            throw err;
        } finally {
            client.release();
        }
    } catch (error) {
        console.error('Signup Error:', error);
        if (error.code === '23505') {
            return res.status(400).json({ error: 'Email already exists' });
        }
        res.status(500).json({ error: 'Internal server error' });
    }
};

exports.login = async (req, res) => {
    const { email, password } = req.body;

    if (!email || !password) {
        return res.status(400).json({ error: 'Email and password are required' });
    }

    try {
        // 1. Find user by email
        const userResult = await db.query('SELECT * FROM users WHERE email = $1', [email]);

        if (userResult.rows.length === 0) {
            return res.status(401).json({ error: 'Invalid email or password' });
        }

        const user = userResult.rows[0];

        // 2. Compare passwords
        const isMatch = await bcrypt.compare(password, user.password);
        if (!isMatch) {
            return res.status(401).json({ error: 'Invalid email or password' });
        }

        // 3. Generate JWT Token
        const token = jwt.sign(
            {
                id: user.id,
                email: user.email,
                schemaName: user.schema_name
            },
            process.env.JWT_SECRET,
            { expiresIn: '24h' }
        );

        res.json({
            message: 'Login successful',
            token,
            user: {
                id: user.id,
                email: user.email,
                schemaName: user.schema_name
            }
        });
    } catch (error) {
        console.error('Login Error:', error);
        res.status(500).json({ error: 'Internal server error' });
    }
};
