'use client';

import React from 'react';
import Link from 'next/link';
import {
    ArrowLeft,
    MessageCircle,
    HelpCircle,
    LifeBuoy,
    Mail,
    MessagesSquare,
    Code2,
    Users,
    ExternalLink,
    Search
} from 'lucide-react';
import styles from '../docs-styles.module.css';

export default function HelpPage() {
    return (
        <div className={styles.docsContainer}>
            <div className={styles.docsLayout}>
                {/* Sidebar */}
                <aside className={styles.sidebar}>
                    <Link href="/" className={styles.backLink}>
                        <ArrowLeft size={16} /> Back to Dashboard
                    </Link>

                    <nav className={styles.navGroup}>
                        <div className={styles.navTitle}>Support</div>
                        <div className={styles.navItemActive}>FAQ</div>
                        <div className={styles.navItem}>Contact Us</div>
                        <div className={styles.navItem}>Community</div>
                    </nav>
                </aside>

                {/* Main Content */}
                <main className={styles.content}>
                    <header className={styles.hero}>
                        <div className={styles.badge}>Customer Success</div>
                        <h1>Help Center.</h1>
                        <p>
                            Everything you need to troubleshoot and master SQLens. Can't find what you're looking for?
                            Reach out to our engineering team.
                        </p>
                    </header>

                    {/* Section: FAQ */}
                    <section className={styles.section}>
                        <h2><HelpCircle size={28} color="var(--brand-pink)" /> Frequently Asked Questions</h2>

                        <div className={styles.featureGrid}>
                            <div className={styles.card}>
                                <h3>Is my data safe?</h3>
                                <p>Yes. Every user operates in a strictly isolated PostgreSQL schema. Your queries and data never touch other tenants.</p>
                            </div>
                            <div className={styles.card}>
                                <h3>Can I connect my own DB?</h3>
                                <p>Currently, SQLens provides managed sandboxes. External database node connection is available in the Enterprise tier.</p>
                            </div>
                            <div className={styles.card}>
                                <h3>How does the AI work?</h3>
                                <p>We use Gemini 1.5 Flash to analyze the JSON execution plans generated by your queries, correlating them with best practices.</p>
                            </div>
                            <div className={styles.card}>
                                <h3>What is the query limit?</h3>
                                <p>Free tier users can execute up to 500 queries per day. For higher limits, contact our sales team.</p>
                            </div>
                        </div>
                    </section>

                    {/* Section: Contact */}
                    <section className={styles.section}>
                        <h2><LifeBuoy size={28} color="#00E4FF" /> Direct Support</h2>
                        <div className={styles.infoBox}>
                            <MessageCircle size={20} />
                            <div>
                                Our engineers are available for live architectural reviews for all Pro and Enterprise customers.
                            </div>
                        </div>

                        <div style={{ display: 'flex', gap: '16px', marginTop: '32px' }}>
                            <a href="mailto:support@sqlens.com" className={styles.card} style={{ flex: 1, textDecoration: 'none', textAlign: 'center' }}>
                                <Mail size={24} style={{ margin: '0 auto 12px' }} />
                                <h3>Email Support</h3>
                                <p>24h response time</p>
                            </a>
                            <a href="https://linkedin.com/in/chaheltanna" className={styles.card} style={{ flex: 1, textDecoration: 'none', textAlign: 'center' }}>
                                <Users size={24} style={{ margin: '0 auto 12px' }} />
                                <h3>LinkedIn</h3>
                                <p>Professional network</p>
                            </a>
                            <a href="https://github.com/sqlens" className={styles.card} style={{ flex: 1, textDecoration: 'none', textAlign: 'center' }}>
                                <Code2 size={24} style={{ margin: '0 auto 12px' }} />
                                <h3>GitHub</h3>
                                <p>Issue tracking</p>
                            </a>
                        </div>
                    </section>

                    <footer style={{ padding: '60px 0', borderTop: '1px solid var(--border)', textAlign: 'center' }}>
                        <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem' }}>
                            &copy; 2026 SQLens Help & Support.
                        </p>
                    </footer>
                </main>
            </div>
        </div>
    );
}
